# Generated by Django 5.1.5 on 2025-07-08 19:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название ступени обучения",
                        max_length=100,
                        verbose_name="Название ступени",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Краткое обозначение ступени",
                        max_length=20,
                        verbose_name="Краткое название",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Порядок следования ступени", verbose_name="Порядок"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Описание ступени",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Ступень активна и используется",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "Ступень",
                "verbose_name_plural": "Ступени",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Полное название предмета",
                        max_length=200,
                        verbose_name="Название предмета",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Краткое обозначение предмета",
                        max_length=50,
                        verbose_name="Краткое название",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Уникальный код предмета",
                        max_length=20,
                        unique=True,
                        verbose_name="Код предмета",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Описание предмета",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Предмет активен и используется",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subsidiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Полное название филиала",
                        max_length=200,
                        verbose_name="Название филиала",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Краткое обозначение филиала",
                        max_length=50,
                        verbose_name="Краткое название",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Полный адрес филиала", verbose_name="Адрес"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Контактный телефон",
                        max_length=20,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Контактный email",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Филиал активен и используется",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "Филиал",
                "verbose_name_plural": "Филиалы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Полное название курса",
                        max_length=200,
                        verbose_name="Название курса",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Краткое обозначение курса",
                        max_length=50,
                        verbose_name="Краткое название",
                    ),
                ),
                (
                    "duration_hours",
                    models.PositiveIntegerField(
                        help_text="Общая продолжительность курса в академических часах",
                        verbose_name="Продолжительность (часы)",
                    ),
                ),
                (
                    "lesson_duration_minutes",
                    models.PositiveIntegerField(
                        default=45,
                        help_text="Стандартная длительность урока в минутах",
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="Длительность урока (минуты)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Описание курса", verbose_name="Описание"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Курс активен и используется",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "level",
                    models.ForeignKey(
                        help_text="Ступень обучения",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="core.level",
                        verbose_name="Ступень",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Предмет, к которому относится курс",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="core.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["level__order", "subject__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название типового пакета курсов",
                        max_length=200,
                        verbose_name="Название пакета",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Описание пакета", verbose_name="Описание"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Пакет активен и используется",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "level",
                    models.ForeignKey(
                        help_text="Ступень обучения",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="core.level",
                        verbose_name="Ступень",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пакет курсов",
                "verbose_name_plural": "Пакеты курсов",
                "ordering": ["level__order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PackageCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours_per_week",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Количество часов в неделю для данного курса",
                        verbose_name="Часов в неделю",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Курс обязателен для изучения",
                        verbose_name="Обязательный",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Порядок следования курса в пакете",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.package",
                        verbose_name="Пакет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс в пакете",
                "verbose_name_plural": "Курсы в пакетах",
                "ordering": ["package", "order"],
                "unique_together": {("package", "course")},
            },
        ),
        migrations.AddField(
            model_name="package",
            name="courses",
            field=models.ManyToManyField(
                help_text="Курсы, входящие в пакет",
                through="core.PackageCourse",
                to="core.course",
                verbose_name="Курсы",
            ),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Уникальный табельный номер сотрудника",
                        max_length=50,
                        unique=True,
                        verbose_name="Табельный номер",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Контактный телефон",
                        max_length=20,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "max_hours_per_week",
                    models.PositiveIntegerField(
                        default=40,
                        help_text="Максимальная учебная нагрузка в неделю",
                        verbose_name="Максимум часов в неделю",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Учитель активен и может вести занятия",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        help_text="Предметы, которые преподаёт учитель",
                        related_name="teachers",
                        to="core.subject",
                        verbose_name="Предметы",
                    ),
                ),
                (
                    "subsidiary",
                    models.ForeignKey(
                        help_text="Основной филиал работы",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachers",
                        to="core.subsidiary",
                        verbose_name="Филиал",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Связанный пользователь системы",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Учитель",
                "verbose_name_plural": "Учителя",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название или номер кабинета",
                        max_length=100,
                        verbose_name="Название кабинета",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Максимальное количество учащихся",
                        verbose_name="Вместимость",
                    ),
                ),
                (
                    "equipment",
                    models.TextField(
                        blank=True,
                        help_text="Описание доступного оборудования",
                        verbose_name="Оборудование",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Кабинет активен и может использоваться",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Предметы, для которых подходит кабинет",
                        related_name="rooms",
                        to="core.subject",
                        verbose_name="Предметы",
                    ),
                ),
                (
                    "subsidiary",
                    models.ForeignKey(
                        help_text="Филиал, в котором находится кабинет",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="core.subsidiary",
                        verbose_name="Филиал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кабинет",
                "verbose_name_plural": "Кабинеты",
                "ordering": ["subsidiary__name", "name"],
                "unique_together": {("subsidiary", "name")},
            },
        ),
    ]
