# Generated by Django 5.1.5 on 2025-07-17 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="level",
            options={
                "ordering": ["subsidiary", "order"],
                "verbose_name": "Ступень",
                "verbose_name_plural": "Ступени",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": ["subsidiary", "name"],
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
            },
        ),
        migrations.AddField(
            model_name="level",
            name="subsidiary",
            field=models.ForeignKey(
                default=1,
                help_text="Филиал, в котором действует ступень",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="levels",
                to="core.subsidiary",
                verbose_name="Филиал",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="subsidiary",
            field=models.ForeignKey(
                default=1,
                help_text="Филиал, в котором преподается предмет",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="core.subsidiary",
                verbose_name="Филиал",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(
                help_text="Уникальный код предмета",
                max_length=20,
                verbose_name="Код предмета",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="level",
            unique_together={("subsidiary", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("subsidiary", "code")},
        ),
    ]
