# Generated by Django 5.1.5 on 2025-07-20 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_level_options_alter_subject_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="subsidiary",
            field=models.ForeignKey(
                help_text="Филиал, в котором действует ступень",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="levels",
                to="core.subsidiary",
                verbose_name="Филиал",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subsidiary",
            field=models.ForeignKey(
                help_text="Филиал, в котором преподается предмет",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="core.subsidiary",
                verbose_name="Филиал",
            ),
        ),
    ]
