# Generated by Django 5.1.5 on 2025-07-20 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_remove_student_group_student_groups_lesson_and_more"),
        ("schedule", "0002_remove_scheduledevent_teacher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledevent",
            name="group",
            field=models.ForeignKey(
                help_text="Группа, участвующая в событии",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_events",
                to="groups.group",
                verbose_name="Группа",
            ),
        ),
    ]
