# Generated by Django 5.1.5 on 2025-07-17 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_level_options_alter_subject_options_and_more"),
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningMaterialCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название коллекции учебных материалов",
                        max_length=200,
                        verbose_name="Название коллекции",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Описание коллекции",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Коллекция активна и используется",
                        verbose_name="Активна",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Предмет, к которому относится коллекция",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_collections",
                        to="core.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Коллекция материалов",
                "verbose_name_plural": "Коллекции материалов",
                "ordering": ["subject", "name"],
            },
        ),
        migrations.AddField(
            model_name="learningmaterialnode",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                help_text="Коллекция, к которой относится узел",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="learning.learningmaterialcollection",
                verbose_name="Коллекция",
            ),
        ),
    ]
