# Generated by Django 5.1.5 on 2025-07-20 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_learningmaterialcollection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningmaterialnode",
            name="collection",
            field=models.ForeignKey(
                help_text="Коллекция, к которой относится узел",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="learning.learningmaterialcollection",
                verbose_name="Коллекция",
            ),
        ),
    ]
